version: "3.8"

services:
    docker-app:
        container_name: docker-app-dev
        build:
            context: .
        env_file:
            - ./.env
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        ports:
            - "9000:9000"


    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - docker-app

    database:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data: ~
